version: '3.1'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: tu_usuario
      POSTGRES_PASSWORD: Password123!
      POSTGRES_DB: tu_base_de_datos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: darioalejandrovv@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Password123!
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
